namespace Application.Interfaces
{
    /// <summary>
    /// Abstraction for correlation context management across async operations.
    /// Provides access to LogId and CorrelationId for distributed tracing.
    /// 
    /// This interface follows the Dependency Inversion Principle (SOLID):
    /// - Application layer depends on the abstraction (this interface)
    /// - Infrastructure layer implements the concrete details (AsyncLocal, etc.)
    /// </summary>
    public interface ICorrelationContext
    {
        /// <summary>
        /// Unique LogId for this specific HTTP request.
        /// Generated by this API.
        /// </summary>
        Guid? LogId { get; set; }

        /// <summary>
        /// CorrelationId shared across multiple APIs in the user journey.
        /// Propagated via X-Correlation-Id header or generated by the first API.
        /// </summary>
        Guid? CorrelationId { get; set; }

        /// <summary>
        /// Name of the service that generated the log (from configuration).
        /// </summary>
        string? ServiceName { get; set; }

        /// <summary>
        /// UserId of the authenticated user (if available).
        /// </summary>
        string? UserId { get; set; }

        /// <summary>
        /// Clears the current context (useful for testing).
        /// </summary>
        void Clear();
    }
}
